[package]
name = "ccloader-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serialport = { version="4.2.0" }
retry = "2.0.0"
crc = "3.0.1"